[2021-04-21 20:06:21,102] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T01:10:00+00:00 [queued]>
[2021-04-21 20:06:21,170] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T01:10:00+00:00 [queued]>
[2021-04-21 20:06:21,172] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:06:21,174] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-21 20:06:21,176] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:06:21,216] {taskinstance.py:1063} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2021-04-19T01:10:00+00:00
[2021-04-21 20:06:21,229] {standard_task_runner.py:52} INFO - Started process 112 to run task
[2021-04-21 20:06:21,261] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', '2021-04-19T01:10:00+00:00', '--job-id', '27', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmp6loi2ae3', '--error-file', '/tmp/tmpbk09c729']
[2021-04-21 20:06:21,268] {standard_task_runner.py:77} INFO - Job 27: Subtask docker_op_tester
[2021-04-21 20:06:21,450] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.docker_op_tester 2021-04-19T01:10:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:06:21,608] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T01:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T01:10:00+00:00
[2021-04-21 20:06:21,638] {taskinstance.py:1455} ERROR - API versions below 1.21 are no longer supported by this library.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/docker/operators/docker.py", line 282, in execute
    self.cli = self._get_cli()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/docker/operators/docker.py", line 314, in _get_cli
    return APIClient(base_url=self.docker_url, version=self.api_version, tls=tls_config)
  File "/home/airflow/.local/lib/python3.6/site-packages/docker/api/client.py", line 202, in __init__
    'library.'.format(MINIMUM_DOCKER_API_VERSION)
docker.errors.InvalidVersion: API versions below 1.21 are no longer supported by this library.
[2021-04-21 20:06:21,642] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20210419T011000, start_date=20210421T200621, end_date=20210421T200621
[2021-04-21 20:06:21,721] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-21 20:12:26,858] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T01:10:00+00:00 [queued]>
[2021-04-21 20:12:26,880] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T01:10:00+00:00 [queued]>
[2021-04-21 20:12:26,881] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:12:26,881] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-21 20:12:26,882] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:12:26,890] {taskinstance.py:1063} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2021-04-19T01:10:00+00:00
[2021-04-21 20:12:26,894] {standard_task_runner.py:52} INFO - Started process 105 to run task
[2021-04-21 20:12:26,899] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', '2021-04-19T01:10:00+00:00', '--job-id', '75', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmpqta86pql', '--error-file', '/tmp/tmpjwilwyu_']
[2021-04-21 20:12:26,900] {standard_task_runner.py:77} INFO - Job 75: Subtask docker_op_tester
[2021-04-21 20:12:26,947] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.docker_op_tester 2021-04-19T01:10:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:12:26,985] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T01:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T01:10:00+00:00
[2021-04-21 20:12:26,995] {docker.py:289} INFO - Pulling docker image centos:latest
[2021-04-21 20:12:31,563] {docker.py:303} INFO - latest: Pulling from library/centos
[2021-04-21 20:12:33,725] {docker.py:303} INFO - 7a0437f04f83: Pulling fs layer
[2021-04-21 20:12:33,727] {docker.py:303} INFO - 7a0437f04f83: Downloading
[2021-04-21 20:12:36,434] {docker.py:303} INFO - 7a0437f04f83: Verifying Checksum
[2021-04-21 20:12:36,436] {docker.py:303} INFO - 7a0437f04f83: Download complete
[2021-04-21 20:12:36,506] {docker.py:303} INFO - 7a0437f04f83: Extracting
[2021-04-21 20:12:40,221] {docker.py:303} INFO - 7a0437f04f83: Pull complete
[2021-04-21 20:12:40,308] {docker.py:298} INFO - Digest: sha256:5528e8b1b1719d34604c87e11dcd1c0a20bedf46e83b5632cdeac91b8c04efc1
[2021-04-21 20:12:40,309] {docker.py:298} INFO - Status: Image is up to date for centos:latest
[2021-04-21 20:12:40,476] {docker.py:224} INFO - Starting docker container from image centos:latest
[2021-04-21 20:13:11,415] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20210419T011000, start_date=20210421T201226, end_date=20210421T201311
[2021-04-21 20:13:11,441] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-04-21 20:13:11,465] {local_task_job.py:146} INFO - Task exited with return code 0
