[2021-04-23 17:03:48,038] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ks-2-example_kubernetes_pod.task-one 2021-04-23T17:03:47.227243+00:00 [queued]>
[2021-04-23 17:03:48,058] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ks-2-example_kubernetes_pod.task-one 2021-04-23T17:03:47.227243+00:00 [queued]>
[2021-04-23 17:03:48,060] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 17:03:48,060] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-23 17:03:48,061] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 17:03:48,071] {taskinstance.py:1063} INFO - Executing <Task(KubernetesPodOperator): task-one> on 2021-04-23T17:03:47.227243+00:00
[2021-04-23 17:03:48,076] {standard_task_runner.py:52} INFO - Started process 249 to run task
[2021-04-23 17:03:48,080] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ks-2-example_kubernetes_pod', 'task-one', '2021-04-23T17:03:47.227243+00:00', '--job-id', '813', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kubernetesOperator.py', '--cfg-path', '/tmp/tmpb3h6w_c1', '--error-file', '/tmp/tmpvlk5hr1c']
[2021-04-23 17:03:48,081] {standard_task_runner.py:77} INFO - Job 813: Subtask task-one
[2021-04-23 17:03:48,142] {logging_mixin.py:104} INFO - Running <TaskInstance: ks-2-example_kubernetes_pod.task-one 2021-04-23T17:03:47.227243+00:00 [running]> on host 5af2b1cab26e
[2021-04-23 17:03:48,187] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ks-2-example_kubernetes_pod
AIRFLOW_CTX_TASK_ID=task-one
AIRFLOW_CTX_EXECUTION_DATE=2021-04-23T17:03:47.227243+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-23T17:03:47.227243+00:00
[2021-04-23 17:03:48,189] {taskinstance.py:1455} ERROR - Service host/port is not set.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py", line 304, in execute
    config_file=self.config_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/kubernetes/kube_client.py", line 126, in get_kube_client
    client_conf = _get_kube_config(in_cluster, cluster_context, config_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/kubernetes/kube_client.py", line 40, in _get_kube_config
    config.load_incluster_config()
  File "/home/airflow/.local/lib/python3.6/site-packages/kubernetes/config/incluster_config.py", line 94, in load_incluster_config
    cert_filename=SERVICE_CERT_FILENAME).load_and_set()
  File "/home/airflow/.local/lib/python3.6/site-packages/kubernetes/config/incluster_config.py", line 45, in load_and_set
    self._load_config()
  File "/home/airflow/.local/lib/python3.6/site-packages/kubernetes/config/incluster_config.py", line 51, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.
[2021-04-23 17:03:48,192] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=ks-2-example_kubernetes_pod, task_id=task-one, execution_date=20210423T170347, start_date=20210423T170348, end_date=20210423T170348
[2021-04-23 17:03:48,216] {local_task_job.py:146} INFO - Task exited with return code 1
