[2021-04-21 20:06:19,629] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T00:30:00+00:00 [queued]>
[2021-04-21 20:06:19,673] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T00:30:00+00:00 [queued]>
[2021-04-21 20:06:19,674] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:06:19,675] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-21 20:06:19,675] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:06:19,698] {taskinstance.py:1063} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2021-04-19T00:30:00+00:00
[2021-04-21 20:06:19,718] {standard_task_runner.py:52} INFO - Started process 90 to run task
[2021-04-21 20:06:19,738] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', '2021-04-19T00:30:00+00:00', '--job-id', '16', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmp2kso_zy4', '--error-file', '/tmp/tmpsr91s_ai']
[2021-04-21 20:06:19,741] {standard_task_runner.py:77} INFO - Job 16: Subtask docker_op_tester
[2021-04-21 20:06:19,843] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.docker_op_tester 2021-04-19T00:30:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:06:19,975] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T00:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T00:30:00+00:00
[2021-04-21 20:06:19,980] {taskinstance.py:1455} ERROR - API versions below 1.21 are no longer supported by this library.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/docker/operators/docker.py", line 282, in execute
    self.cli = self._get_cli()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/docker/operators/docker.py", line 314, in _get_cli
    return APIClient(base_url=self.docker_url, version=self.api_version, tls=tls_config)
  File "/home/airflow/.local/lib/python3.6/site-packages/docker/api/client.py", line 202, in __init__
    'library.'.format(MINIMUM_DOCKER_API_VERSION)
docker.errors.InvalidVersion: API versions below 1.21 are no longer supported by this library.
[2021-04-21 20:06:19,987] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20210419T003000, start_date=20210421T200619, end_date=20210421T200619
[2021-04-21 20:06:20,129] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-21 20:12:25,361] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T00:30:00+00:00 [queued]>
[2021-04-21 20:12:25,393] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: docker_sample.docker_op_tester 2021-04-19T00:30:00+00:00 [queued]>
[2021-04-21 20:12:25,395] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:12:25,395] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-21 20:12:25,396] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-21 20:12:25,422] {taskinstance.py:1063} INFO - Executing <Task(DockerOperator): docker_op_tester> on 2021-04-19T00:30:00+00:00
[2021-04-21 20:12:25,429] {standard_task_runner.py:52} INFO - Started process 79 to run task
[2021-04-21 20:12:25,435] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'docker_sample', 'docker_op_tester', '2021-04-19T00:30:00+00:00', '--job-id', '64', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dockerOperator.py', '--cfg-path', '/tmp/tmpriybw5l4', '--error-file', '/tmp/tmpx3oluxm6']
[2021-04-21 20:12:25,440] {standard_task_runner.py:77} INFO - Job 64: Subtask docker_op_tester
[2021-04-21 20:12:25,556] {logging_mixin.py:104} INFO - Running <TaskInstance: docker_sample.docker_op_tester 2021-04-19T00:30:00+00:00 [running]> on host 5af2b1cab26e
[2021-04-21 20:12:25,637] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=docker_sample
AIRFLOW_CTX_TASK_ID=docker_op_tester
AIRFLOW_CTX_EXECUTION_DATE=2021-04-19T00:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-19T00:30:00+00:00
[2021-04-21 20:12:25,665] {docker.py:289} INFO - Pulling docker image centos:latest
[2021-04-21 20:12:30,538] {docker.py:303} INFO - latest: Pulling from library/centos
[2021-04-21 20:12:32,979] {docker.py:303} INFO - 7a0437f04f83: Pulling fs layer
[2021-04-21 20:12:32,981] {docker.py:303} INFO - 7a0437f04f83: Downloading
[2021-04-21 20:12:36,434] {docker.py:303} INFO - 7a0437f04f83: Verifying Checksum
[2021-04-21 20:12:36,435] {docker.py:303} INFO - 7a0437f04f83: Download complete
[2021-04-21 20:12:36,506] {docker.py:303} INFO - 7a0437f04f83: Extracting
[2021-04-21 20:12:40,223] {docker.py:303} INFO - 7a0437f04f83: Pull complete
[2021-04-21 20:12:40,423] {docker.py:298} INFO - Digest: sha256:5528e8b1b1719d34604c87e11dcd1c0a20bedf46e83b5632cdeac91b8c04efc1
[2021-04-21 20:12:40,425] {docker.py:298} INFO - Status: Image is up to date for centos:latest
[2021-04-21 20:12:40,494] {docker.py:224} INFO - Starting docker container from image centos:latest
[2021-04-21 20:13:12,984] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=docker_sample, task_id=docker_op_tester, execution_date=20210419T003000, start_date=20210421T201225, end_date=20210421T201312
[2021-04-21 20:13:13,058] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-21 20:13:13,103] {local_task_job.py:146} INFO - Task exited with return code 0
